version: '3'
services:
  backend:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    links:
      - mongo:mongo
    volumes:
      - ./backend:/srv/app
    ports:
      - '1337:1337'
    command: bash -c "npm run build && npm run seed && npm run develop"

  frontend:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    environment: 
      REACT_APP_BACKEND_URL: http://localhost:1337
    links:
      - backend:backend
    depends_on: 
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    command: npm run develop

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: strapi
    volumes:
      - /data/db
    ports:
      - '27017:27017'